Fix _MPResterLegacy tests in pymatgen/ext/tests/test_matproj.py failing due to new API key (#2700)
* pymatgen/ext/tests/test_matproj.py raise ValueError with specific err msg if 15 <= len(PMG_MAPI_KEY) <= 17

* pymatgen/ext/tests/test_*.py refactor skipIf website_is_up to website_down check

* fix pymatgen/ext/tests/test_matproj.py:402: AssertionError

assert mo_s3_112[0]["gb_energy"] == pytest.approx(0.47965)
E       assert 0.4796547330588574 == 0.47965 � 4.8e-07
E         comparison failed
E         Obtained: 0.4796547330588574
E         Expected: 0.47965 � 4.8e-07

* remove shebangs from test files

* fix TypeError: MPRester.__init__() got multiple values for argument 'api_key' from MPRester('xxxxxxxxxx')