speed up `bader_caller` and `chargemol_caller` (#3192)
* do not copy large files like CHGCAR, into tempfolder,use `monty.tempfile.ScratchdDr` context manager

* add `chgref_filename` back

* chargemol: use symbolic link to link large files to temporary folder

* chargemol: use symbolic link to link large files to temporary folder

* decompress file to temporary file only if neccessary

* clean code and revise docstring

* clean code and revise docstring

* fix mypy

* use `monty.shutil.decompress_file`

* use `PymatgenTest.tmp_path` for test

* shorten bader + chargemol RuntimeError message, show chargemol exe path in err msg

* f-str path construction

* use self.tmp_path fixture directly (is already function scoped)

* simplify file path handling

* fix assert analysis.data[0]["charge"] == approx(6.6136782, abs=1e-3)
E       assert 6.395428 == 6.6136782 ± 1.0e-03
E         comparison failed
E         Obtained: 6.395428
E         Expected: 6.6136782 ± 1.0e-03

/home/runner/work/pymatgen/pymatgen/tests/command_line/test_bader_caller.py:37: AssertionError

* add type hints to bader_caller.py

* fix kwarg bader_exe_path (wasn't actually used)

* use f-str formatting in atom_chgcars

* fix test_from_path, was broken due to decompressing files deletes the compressed version which can't happen twice in same directory

* revert assert analysis.data[0]["charge"] == approx(6.395428, abs=1e-3)
E       assert 6.613678 == 6.395428 ± 1.0e-03

and fix mypy

---------

Co-authored-by: Janosh Riebesell <janosh.riebesell@gmail.com>